Uncomment ANYMAIL config for production
This is required.

```
anymail.exceptions.AnymailConfigurationError: You must set ANYMAIL_MAILGUN_API_KEY or ANYMAIL = {'MAILGUN_API_KEY': ...} or MAILGUN_API_KEY in your Django settings
```